"""title_lenght

Revision ID: 7773e2f0e0a7
Revises: a4ec987200dd
Create Date: 2024-11-15 17:08:30.530497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7773e2f0e0a7'
down_revision: Union[str, None] = 'a4ec987200dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
